/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all saved Todos */
        get: operations["listTodos"];
        put?: never;
        /** Create a Todo with a new stable identity */
        post: operations["createTodo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Atomically replace the business fields of an existing Todo */
        put: operations["updateTodo"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Must contain non-whitespace text and at most 300 Unicode grapheme clusters. Never silently truncated. */
        Task: string;
        /** @description May be empty; at most 1000 Unicode grapheme clusters. Never silently truncated. */
        Description: string;
        /**
         * @description Overdue is system-managed. Only incomplete Todos with server time strictly after dueAt become overdue; completed Todos are exempt.
         * @enum {string}
         */
        TodoStatus: "incomplete" | "completed" | "overdue";
        /**
         * @default incomplete
         * @enum {string}
         */
        ManualTodoStatus: "incomplete" | "completed";
        /**
         * Format: date-time
         * @description Editable deadline as an RFC 3339 timestamp, returned in UTC. Null means no deadline; past deadlines are valid.
         */
        DueAt: string | null;
        TodoInput: {
            task: components["schemas"]["Task"];
            description: components["schemas"]["Description"];
            status: components["schemas"]["ManualTodoStatus"];
            dueAt?: components["schemas"]["DueAt"];
        };
        /** @description Omitting dueAt preserves it; null clears it. Omitting status preserves the current state subject to system transitions. Overdue records can recover to incomplete only by saving a changed deadline at or after server time, or clearing it. */
        TodoUpdate: {
            task: components["schemas"]["Task"];
            description: components["schemas"]["Description"];
            status?: components["schemas"]["ManualTodoStatus"];
            dueAt?: components["schemas"]["DueAt"];
        };
        Todo: {
            /** @description Unique within the collection, allocated on create, unchanged by edits. */
            id: string;
            task: components["schemas"]["Task"];
            description: components["schemas"]["Description"];
            status: components["schemas"]["TodoStatus"];
            /**
             * Format: date-time
             * @description UTC time of the first successful creation, assigned by the server clock and serialized as RFC 3339. Never changes on update or load; rejected in client input.
             */
            readonly createdAt: string;
            dueAt: components["schemas"]["DueAt"];
        };
        ApiError: {
            /** @enum {string} */
            code: "validation_error" | "not_found" | "status_conflict" | "invalid_json" | "unsupported_media_type" | "payload_too_large" | "service_error";
            message: string;
            fields?: {
                [key: string]: string;
            };
            current?: components["schemas"]["Todo"];
        };
    };
    responses: {
        /** @description Malformed JSON, unsupported content type, or a request exceeding the transport size limit. */
        RequestError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Invalid fields. Saved data is unchanged. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description The operation failed. A failed write does not partially change saved data. */
        ServiceError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: never;
    requestBodies: {
        TodoInput: {
            content: {
                "application/json": components["schemas"]["TodoInput"];
            };
        };
        TodoUpdate: {
            content: {
                "application/json": components["schemas"]["TodoUpdate"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTodos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current collection, including an empty array when no records exist. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"][];
                };
            };
            500: components["responses"]["ServiceError"];
        };
    };
    createTodo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TodoInput"];
        responses: {
            /** @description The complete Todo after an atomic save. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            400: components["responses"]["RequestError"];
            413: components["responses"]["RequestError"];
            415: components["responses"]["RequestError"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["ServiceError"];
        };
    };
    updateTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The stable opaque ID returned by the service. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TodoUpdate"];
        responses: {
            /** @description The complete saved Todo with its identity and creation time unchanged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            400: components["responses"]["RequestError"];
            /** @description No Todo has this ID. An update never creates a record. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The current Todo is overdue; manual status edits were not applied. Retry deadline/content edits without status. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"] & Record<string, never>;
                };
            };
            413: components["responses"]["RequestError"];
            415: components["responses"]["RequestError"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["ServiceError"];
        };
    };
}
